### ISSUE TITLE
Environment variable management issue

### ISSUE THREAD

**Issue by pablocarle** [zowe/launcher#76]
With example in `zowe.yaml` like:

```yaml
  environments:
    APIML_SECURITY_SAF_URLS_AUTHENTICATE: https://usilca32.lvn.broadcom.net:40030/zss/api/v1/saf/authenticate
    SAMP_5: TE\"ST
    SAMP_6: "TE\"ST"
    SAMP_7: TE"ST
    SAMP_8: TE " ST
    SAMP_9: "TE \" ST"
```

and STC-defined variables:

```jcl
//STDENV   DD  *
_CEE_ENVFILE_CONTINUATION=\
_CEE_RUNOPTS=HEAPPOOLS(OFF)
SAMP_1="TE\"ST"
SAMP_2=TE\"ST
SAMP_3=TE \" ST
SAMP_4="TE \" ST"
CONFIG=/z/zwesvusr/zowe/zowe-vnightly-v2/zowe.yaml
/*
```

`SAMP_5` is escaped incorrectly for the prepare instance and get-launch-components execution, thus failing startup:

`SAMP_5="TE\\"ST"`
