### ISSUE TITLE
Need to double parmlib member name?

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/launcher#87]
### Setting
`/z/users/z280` symbolic link to some valid `zowe.yaml`

ZOWE.PARMLIB(YAML):
```
zowe:                 
  environments:       
    SECRET_VALUE: 1   
  useConfigmgr: true  
```

Launcher STDENV:
```
CONFIG=FILE(/z/users/z280):\              
PARMLIB(ZOWE.PARMLIB(YAML))
```
This returns `Error: malformed PARMLIB syntax for FILE(/z/users/z280):PARMLIB(ZOWE.PARMLIB).`

```
CONFIG=FILE(/z/users/z280):\              
PARMLIB(ZOWE.PARMLIB(YAML)(YAML))
```
This double member name is working fine and you can see defined env variable was succesfuly processed:

```
ZWE_components_gateway_debug=false        
ZWE_zowe_environments_SECRET_VALUE=1      
ZWE_PRIVATE_CLI_LIBRARY_LOADED=true       
```

This was found in 2.8.0, I will re-test this for zowe 2.10.0 (when GA) and update/close this issue.
